### PR TITLE
write a check to ensure only 64 bit architecture packages are install…

### PR DESCRIPTION
**Pull request by jhshin9**
…ed #14

https://github.com/cloudera-ps/prereq-checks/issues/14

### CODE REVIEW

**Comment by jhshin9** [comment]
@jamestyj @kmizumar @myloginid Please, review and merge. Thanks.

**Comment by kmizumar** [comment]
@jhshin9 I don't have write access to this repo.

**Comment by jhshin9** [comment]
@kmizumar Thank you for your review but I tested on my aws(centos 7.2) without '\t' on the line.
The result is below:
screen shot 2017-06-27 at 11 32 44 am

**Comment by kmizumar** [comment]
`rpm -qa --queryformat '%{NAME} %{ARCH}\n\t' | grep 'i[6543]86' | cut -d' ' -f1`

Can I see the result of the above command in your environment?

**Comment by kmizumar** [comment]
function check_only_64bit_packages_installed() {
      local packages_32bit=`rpm -qa --queryformat '\t%{NAME} %{ARCH}\n' | grep 'i[6543]86' | cut -d' ' -f1`
      if [ "$packages_32bit" ]; then
        state "Only 64bit packages: 32bit packages are installed:\n$packages_32bit" 1
      else
        state "Only 64bit packages: Only 64bit packages are installed" 0
      fi
    }

Also, check the result with the above definition of check_only_64bit_packages_installed function. Thanks.

**Comment by jhshin9** [comment]
@kmizumar The indent on my aws is good with your code. I will push with it.

**Pull request merged**
