### PR TITLE
Add Vagrant boxes CentOS 6.7 & 7.3 for tests

### PR DESCRIPTION
**Pull request by jamestyj**

### CODE REVIEW

**Comment by kmizumar** [comment]
Confirmed that it works with Vagrant 1.9.7 and vagrant-vmware-fusion plugin (4.0.24).

The vagrant/v bash script assumes the consolidated script file (`prereq-check-single.sh`) exists in the top level directory, but it's not added to this git repository (it's listed in `.gitignore`)

Do you think we should keep ignoring `prereq-check-single.sh` or it should be added to the repository? I think the best way is to create a commit hook to generate it automatically (but I don't know how to implement it right now). Thoughts? @jamestyj @manojsundaram

**Comment by jamestyj** [comment]
I've since added the script to Git, so we're good now. Commit hook would be one way yes but we can figure that out later.

**Comment by kmizumar** [comment]
Didn't see prereq-check-single.sh on the branch so I added it.

**Comment by jamestyj** [comment]
It was in master.

**Comment by kmizumar** [comment]
ah, I see. found this one:

> commit 6e586747a770ccb5635dafd78deb3994a19aea16
> Author: James Tan <jtan@cloudera.com>
> Date:   Fri Aug 18 10:36:23 2017 +0800
> 
>     Add prereq-checks-single.sh to Git
> 
>     This makes it easier to share the single file version, as we can use the direct
>     raw Github link.

**Pull request merged**
